import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import { ThirdwebProvider } from "./components/ThirdwebProvider";
import { Sepolia } from "@thirdweb-dev/chains";



const inter = Inter({ subsets: ['latin'] })





export const metadata = {
  title: 'Lottery 4D',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <ThirdwebProvider 
        activeChain={Sepolia}
        clientId={process.env.NEXT_PUBLIC_THIRDWEB_PROVIDER_CLIENT_ID}
        >
        <body className={inter.className}>
          <Navbar/>  
          {children}

        </body>
      </ThirdwebProvider>
      
    </html>
  )
}
